#pragma once

#define DEF_MONERO_VERSION_TAG "DESVIAN"
#define DEF_MONERO_VERSION "1.0.0"
#define DEF_MONERO_RELEASE_NAME "Desvian Genesis"
#define DEF_MONERO_VERSION_FULL "1.0.0-DESVIAN"
#define DEF_MONERO_VERSION_IS_RELEASE 1
